---
name:             PlayerScale
main:             presentkim\playerscale\PlayerScale
version:          1.2.1
api:              [3.0.0, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
author:           PresentKim
website:          https://github.com/PMMPPlugin/PlayerScale
description:      A plugin set players scale

permissions:
  playerscale.cmd:
    description:  PlayerScale main command
    default:      op
    children:
      playerscale.cmd.default:
        description:  PlayerScale command - default
        default:      op
      playerscale.cmd.set:
        description:  PlayerScale command - set
        default:      op
      playerscale.cmd.list:
        description:  PlayerScale command - list
        default:      op
      playerscale.cmd.lang:
        description:  PlayerScale command - lang
        default:      op
      playerscale.cmd.reload:
        description:  PlayerScale command - reload
        default:      op
      playerscale.cmd.save:
        description:  PlayerScale command - save
        default:      op
...
